function nhanVien(id,ten,email,password,ngaylam,luong,chuc,giolam) {
    this.idNV = id,
    this.tenNV = ten,
    this.email = email,
    this.pass = password,
    this.ngaylam = ngaylam,
    this.luong = luong,
    this.chucvu = chuc,
    this.giolam = giolam;

    //tính tổng lương
    // this.tinhTL = function(luong, chucvu){

    //     if (chucvu) {
    //         return TL = luong * 3;
    //     } else if (chucvu) {
    //         return TL = luong * 2;
    //     } else {
    //         return TL = luong;
    //     }
    // }

    
}